name: OpenHiveBedwars
version: '${project.version}'
main: net.prismarray.openhivebedwars.OpenHiveBedwars
api-version: 1.18
authors: [ Prismary, paulklee2000 ]
description: An open source re-implementation of the Bedwars plugin used on the now closed HiveMC Java Edition server
website: https://github.com/Prismary/openHiveBedwars

commands:
  openhivebedwars:
    usage: /openhivebedwars <help|version|reload>
    description: root command
    aliases: [ ohbw, hbw, bw ]
  team:
    usage: /team <player>
    description: team another player
    aliases: []
  vote:
    usage: /vote <index>
    description: votes for a map in lobby phase
    aliases: [ v ]
  gui:
    usage: /gui [size [title]]
    description: test command for opening several GUI inventories
    aliases: []
